name: Publish Business Sandbox BitesBox

# Controls when the workflow will run
# This workflow is triggered on pushes to the dev branch only.
on:
  pull_request:
   types: [closed]
   branches:
      Mock

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with: 
          node-version: ${{ matrix.node }}

      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Stencil CLI Dependency
        run: npm install -g @bigcommerce/stencil-cli

      - name: Install Dependencies
        run: npm ci
      
      - name: Connect to store
        env:
          URL: ${{ secrets.STENCIL_STORE_URL_BITES_BOX_BUSINESS_SANDBOX }}
          TOKEN: ${{ secrets.STENCIL_ACCESS_TOKEN_BITES_BOX_BUSINESS_SANDBOX }}
        run: stencil init -u $URL -t $TOKEN -p 3000 -h https://api.bigcommerce.com

      - name: Publishing theme to Business-Sandbox Bites Box Store, automatically deleting oldest theme if necessary
        run: stencil push -a Light -d
